### ISSUE TITLE
Nylas Mail lost all email accounts on restart

### ISSUE THREAD

**Issue by djdiaz** [nylas/nylas-mail#3231]
##### Are there any related issues?

No

##### What operating system are you using?
macOS Sierra 10.12.2

##### What version of N1 are you using?
Noted in Nylas Mail 1.0.11 and 1.0.15.

--

I just had a very strange thing happen: Nylas Mail suddenly refused to delete a message (would not delete no matter how many times I tried). I tried restarting the app to see if I could get it to reset, but on restart it asked me to set up from scratch. All my accounts were gone and had to be set up and synced again. Oddly, the email database wasn't lost, so all the emails were still there. Just the accounts were gone.

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not as far as I know, but all accounts are Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

**Comment by jcjan** [comment]
Exact same thing just happened to me this morning. Couldn't delete messages, restarted the app, and all accounts were gone. Nylas Mail 1.0.15 and Sierra 10.12.3.

**Comment by OJFord** [comment]
I cannot even open the app after installing for the first time to move from Pro, I click login with Google, browser suggests it was successful, but the app just shows:

![screen shot 2017-01-29 at 15 14 42](https://cloud.githubusercontent.com/assets/3946014/22405136/b671fe66-e635-11e6-85b2-7771d9817141.png)

I wasn't expecting to have to re-add accounts, but there's no way of getting past this 'welcome' screen to see if it's already there or not.

**Comment by djdiaz** [comment]
It's done it again. Twice in just a few days. Could not delete a thread, and then on restart all mail accounts are gone and Nylas Mail asks to set up from scratch. Now on 1.0.15.

**Comment by light2yellow** [comment]
It did reset for me as well.

**Comment by devdn12** [comment]
Happening to me as well. When i wake my computer up, all the accounts are gone - this is fourth time

**Comment by jstejada** [comment]
thanks for the details everyone, we are currently looking into this
thanks for your patience!

**Comment by jstejada** [comment]
@fonnesbeck I saw on twitter that you were also having this issue, so I'm looping you in this issue

**Comment by jstejada** [comment]
@jcjan @djdiaz was there any error message when you couldn't delete a thread? By deleting threads, do you mean moving them to the `Trash` folder?

if this happens again, could you send me the output of your console via Console.app?

also, in order to diagnose this, when the error happens again, or when you are unable to "delete threads", could you do the following:

1. Open the Activity Window via `cmd+alt+i`
2. In the Activity Window, open Dev Tools via `cmd+alt+w`
3. Select the `Console` tab
4. Send me a screenshot of your `Console` as it is

5. Then, select the `Filter` icon
![image](https://cloud.githubusercontent.com/assets/1271509/22381429/6bbd79f6-e476-11e6-8a06-a5e94acd91b1.png)

6. Then, Filter by Errors
<img width="870" alt="screen shot 2017-01-27 at 9 53 41 am" src="https://cloud.githubusercontent.com/assets/1271509/22381496/ad948504-e476-11e6-951e-719abbc2a1f9.png">

7. Send me a second screenshot of your `Console` filtered by errors

If you prefer not to share the screenshots here, feel free to send them to support@nylas.com and mention Juan. This will help us diagnose this issue.

Thanks!

**Comment by fonnesbeck** [comment]
@jstejada Thanks. Mine was associated with a restart for an unrelated issue (crashing Python kernel). Also on macOS 10.12 and new hardware (Macbook 13").

**Comment by djdiaz** [comment]
@jstejada When I tried to delete a thread, it said "Trashing..." but the message remained in place. Subsequent attempts to delete produced the same result.

I will try to get more debug info as you've noted, but I've basically gone back to N1 for now because this issue is too painful to deal with.

**Comment by jstejada** [comment]
thanks a lot @djdiaz! Let me know if you are able to reproduce on v 1.0.18. You should see an error dialog if Trashing fails now.

Thanks again!

**Comment by jstejada** [comment]
@djdiaz @jcjan  how many accounts were you syncing when this error happened?

**Comment by djdiaz** [comment]
@jstejada Two the first time, three the second time.

**Comment by jstejada** [comment]
@djdiaz when trying to move threads to trash, do they disappear from the list and then come back after a couple of seconds?

**Comment by djdiaz** [comment]
@jstejada Yes. It's all described above in all my earlier comments on this thread.

**Comment by djdiaz** [comment]
@jstejada No. The message just sits there when this happens.

**Comment by light2yellow** [comment]
aaand with .20 pdate the accounts are reset again. -_-

**Comment by jstejada** [comment]
@light2yellow yes, we've identified the problem and are currently working on a fix. We should release the fix soon!

Thanks for your patience!

**Comment by jstejada** [comment]
Hi all, we've just released 1.0.21, and this issue should be fix. If you encounter it again please let us know here. Thanks again for your patience!
