### ISSUE TITLE
Ubuntu version

### ISSUE THREAD

**Issue by opensorceror** [nylas/nylas-mail#3315]
Hello! I was wondering when the Linux version will be released. Is there a roadmap or a Trello board stating a planned release date?

**Comment by jtflynnz** [comment]
There isn't a projected timeline yet (not officially, and not enough info to speculate really), but some others have posted in #3256 with nay info that is currently available.

**Comment by rawkode** [comment]
"Order of weeks, not months" - but very disappointing lack of feedback or updates.

https://github.com/nylas/nylas-mail/issues/3294#issuecomment-281500163

**Comment by ivellios** [comment]
I used some older build for a month on my Ubuntu, but now it stopped working due to being pro in fact... can I turn it off somehow and just use basic features? Or do I have to wait until they release linux version?

**Comment by jtflynnz** [comment]
Unfortunately, the old "Free" model was builing/hosting the service (client + server instances) oneself; there isn't a way to use the prebuilt N1/Pro application and turn it back to "free" because it didn't technically exist prior to the new Nylas-Mail client. I'm also not sure if there is a way to build the the old applicaton and server now, it's somewhat unclear.

________________________________

**Comment by jstejada** [comment]
merging into #3256
