### ISSUE TITLE
Windows Situation

### ISSUE THREAD

**Issue by Stanzilla** [nylas/nylas-mail#3321]
I'm kinda lost when it comes to the current Windows build situation, there is only one Windows Build (1.5) on GitHub releases, the download website is just a newsletter signup and the newer builds on GitHub are numbered lower than 1.5. (1.0.x etc) What exactly is the Windows situation?

**Comment by sachinag** [comment]
Mail is different than Pro. Mail is only available for Mac right now, but Windows and Linux are coming soon!  (Trust me, it's pretty confusing for us too.)

**Comment by ArchangeGabriel** [comment]
@Stanzilla To be more clear, because the above answer is a bit short/confusing from my POV (because Pro and Mail are not even the same kind of things):

– Nylas has currently two price tiers: Nylas Basic and Nylas Pro. Those have nothing to do with OSes on their own, but see below.
– Nylas has currently two email clients: Nylas Mail and Nylas N1. Mail is the one with version in the 1.0.x range, N1 is the one at 1.5.x. N1 is supposed to retire when Mail will support Pro account (currently, N1 only supports Pro AFAIK while Mail only supports Basic). N1 is available for the three OSes, but Mail only for Mac currently (as pointed by @sachinag above).

**Comment by Stanzilla** [comment]
Oh. Yeah, that is super confusing, especially since it's all in the same repo :) Thanks for the explanation though!

**Comment by onlineth** [comment]
Can this issue stay open until Nylas Mail is available for Windows? Or is there another place to track the progression of that?

**Comment by ksec** [comment]
@ArchangeGabriel So client version 1.5x is suppose to retire when client version 1.0.x support the Pro account.
Yes this is super confusion. But I will just wait for Windows version.
