### ISSUE TITLE
No Mail Rules anymore in Nylas Mail ?

### ISSUE THREAD

**Issue by Bergg** [nylas/nylas-mail#3421]
I can't see the Mail Rule in the preferences of Nylas Mail while it's there in N1. Will it come back ? 

##### Are there any related issues?

No that I can see

##### What operating system are you using?
Fedora25

##### What version of Nylas Mail are you using?
 2.0.15-0.1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Exists in N1

**Comment by franzos** [comment]
Apparently this is [planned](https://support.nylas.com/hc/en-us/articles/115005574208-Nylas-Mail-Customer-FAQ).

> The features currently missing from Nylas Mail as of April 2017 are: (1) support for on-premise Microsoft Exchange via ActiveSync, (2) Mail Rules, (3) Thread Sharing, (4) Proposed Meeting Times, (5) Mail Merge, (6) Salesforce integration, and (7) our PGP plugin.  We are working to adding many of these features back to Nylas Mail, with a focus on the most requested features.  However, based on our customer feedback and limited usage we are unlikely to add support for on-premise Microsoft Exchange to Nylas Mail.

**Comment by Bergg** [comment]
right - missed that, thanks @franzos

**Comment by hg2010** [comment]
franzos, when is it expected for mail rules to be added back - even the most basic email clients have that - very surprised this was taken out. We need it!!! :)

**Comment by franzos** [comment]
@hg2010 What email provider are you using? The thing is, virtually all Email providers have email rules, hence I've never actually found them very useful in N1. In fact, the real problem is, that these rules only apply as long as Nylas Mail is running, so while you're on the go, your email remains unsorted.

There are two other feature request, which may be interesting:
Custom rules (IFTTT style) #3165 
Mail Rules by Date #3098 

I'd personally prefer to keep basic rules in Fastmail, however it would be amazing if Nylas Mail could complement these with more advanced rules. For example, I'd like to clear out all email notifications (reminder, tasks, ...) automatically after 7 days - this is not possible with basic rules but also not time sensitive so it may run, whenever I run Nylas Mail.
