### ISSUE TITLE
Add Gmail account = An unforescreen error has occured

### ISSUE THREAD

**Issue by Jipem** [nylas/nylas-mail#3448]
##### Are there any related issues?
#3211

##### What operating system are you using?
Windows 10 version 1607

##### What version of Nylas Mail are you using?
2.0.16

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

--

When I want to add a Gmail account, the authentication page opens correctly on Chrome. But once the procedure is finished, Nylas reports an error : "Sorry, we had trouble logging you in. Please contact support@nylas.com. An unforescreen error has occured. Please try again. If you continue to see this error contact support@nylas.com". Unable to add my Gmail accounts (or G Suite)... (tested several times for several days)

**Comment by kokno** [comment]
I have the same error but I have the two-factor authentification activated, you too ?

**Comment by Jipem** [comment]
Me too, via the Google Authenticator app. But authentication is active via Chrome, and permission is already given for Nylas...

**Comment by jstejada** [comment]
Thanks for your patience! We’ve just released version 2.0.18 which should allow you to authenticate despite the error your are seeing. This error is likely caused by the presence of an antivirus in your system, so if you disable your anti-virus for Nylas Mail, you should stop seeing this error when you authenticate.

Please let me know if you continue having issues. Thanks again for your patience!

**Comment by Jipem** [comment]
Hello,
With Nylas 2.0.18, and without antivirus (Avast), it is OK. Thank you !
